name: Github Action for CTeX-kit Test

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install TeX Live
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz
        cd install-tl-20* && ./install-tl --profile ../.github/workflows/texlive.profile
        cd ..
        tlmgr install adobemapping amsfonts amsmath cjk cjkutils cm ctablestack currfile dvipdfmx environ etex etoolbox euenc fancyhdr fandol filehook fontspec graphics graphics-cfg graphics-def iftex l3build l3experimental l3kernel l3packages latex-bin lm lm-math lualatex-math lualibs luaotfload luatex luatex85 luatexbase luatexja metafont mfware ms oberdiek platex-tools tex tex-ini-files tools trimspaces ucharcat ulem unicode-data uplatex varwidth xcolor xetex xkeyval xunicode
        tlmgr option -- autobackup 0
        tlmgr update --self --all --no-auto-install
        echo $PATH
    - name: Test CTeX
      run: |
        echo $PATH
        ls -al /tmp/texlive/bin/x86_64-linux
        pwd
        ls -al
        cd ctex
        which l3build
        l3build --version
        which tex
        tex --vesion
        which xetex
        xetex --version
        which luatex
        luatex --credits
        pwd
        l3build unpack
        l3build check

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        ls -al
        pwd
        echo $PATH
        echo Add other actions to build,
        echo test, and deploy your project.

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        dir
        cd
        set Path
        echo Add other actions to build,
        echo test, and deploy your project.
