name: Github Action for CTeX-kit Test

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        ls -al
        pwd
        echo $PATH
        echo Add other actions to build,
        echo test, and deploy your project.

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        ls -al
        pwd
        echo $PATH
        echo Add other actions to build,
        echo test, and deploy your project.

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        dir
        cd
        set Path
        echo Add other actions to build,
        echo test, and deploy your project.
